### PR TITLE
A few e-ink fixes

### LINKED ISSUE #17: E-Ink theme
Hi Thanks for building such a fantastic application.  

I have just tried applying the E-Ink theme and noticed that the 'hover' text in menus is not visible - I presume because the font is set to white?  I'm using MS Edge on both my eBook reader and PC and can replicate on both.  Should I be looking for another setting elsewhere to adjust the menu font?

Thanks again

### PR DESCRIPTION
**Pull request by YodaDaCoda**
# Fix side nav text colour
## Before
Screenshot_20240705_132027
## After
Screenshot_20240705_132041

# Fix dropdown text colour
(fixes #17)
## Before:
image
## After:
image

# Fix card background colour

## Before
(this is actually much less readable on an e-ink display than the screenshot shows)
image
## After
image

### CODE REVIEW

**Comment by YodaDaCoda** [comment]
Looks like my editor removed a bunch of spaces on blank lines. Hope that's okay.

**Comment by majora2007** [comment]
Nice fixes. Does the preview image need to be regenerated or the readme need version updating? 

I ask because in v0.8.2 Kavita what's a built-in theme management system.

**Review by majora2007 — APPROVED** [review]

**Comment by majora2007** [comment]
I just checked and there is no preview on record. Can you create one and also update the theme version for v0.8.2 (this will be released within days).

**Comment by YodaDaCoda** [comment]
> update the theme version for v0.8.2

just in the readme?

**Comment by majora2007** [comment]
Correct. Add a preview and update the version in the Readme. The theme manager built into Kavita as of v0.8.2 will read that information out.

image

Once done, I can merge this (and then users will auto-update this theme)

**Comment by YodaDaCoda** [comment]
I added a preview, and a couple other tweaks. 

I had some trouble getting some bits to be the right colour, looks to be due to Kavita's base style. Should I raise an issue for that over on the main Kavita repo or here?

**Comment by majora2007** [comment]
> I added a preview, and a couple other tweaks.
> 
> I had some trouble getting some bits to be the right colour, looks to be due to Kavita's base style. Should I raise an issue for that over on the main Kavita repo or here?

Please do in the main repo. Issues here are for theme issues.

**Pull request merged**
