### PR TITLE
Add a new Overseerr inspired theme

### PR DESCRIPTION
**Pull request by matguitarist**
Overseerr inspired theme

### CODE REVIEW

**Comment by matguitarist** [comment]
Updated the README.md

**Comment by majora2007** [comment]
You have conflicts, i believe you need this for the readme:

```
## Native Themes
| Theme Name | Author | Description                                         | Kavita Compatibility | Preview | 
|------------|--------|-----------------------------------------------------|----------------------|---------|
| Light      | [majora2007](https://github.com/majora2007)    | A light theme for those that don't like dark themes | 0.7.14               | [Preview](https://github.com/Kareadita/Themes/blob/main/Native%20Themes/Light/example.png) |
| Brilliance | [Elry](https://github.com/ElryWeeb)            | A modern theme for e-ink devices (update for E-Ink) | 0.7.14               | [Preview](https://github.com/Kareadita/Themes/blob/main/Native%20Themes/Brilliance/preview.png) |
| Nord       | [ice45core0](https://github.com/ice45core0)    | A dark pastel theme using the Nord color palette    | 0.7.14               | [Preview](https://github.com/Kareadita/Themes/blob/main/Native%20Themes/Nord/preview.png) |
| E-Ink      | [majora2007](https://github.com/majora2007)    | A simplified theme for e-ink devices                | 0.5.2.x              | N/A |
| Dracula    | @Mat#6627                                      | A Dracula inspired theme                            | ?                    | [Preview](https://github.com/Kareadita/Themes/blob/main/Native%20Themes/Dracula/preview.jpg) |
| Overseerr  | [Matguitarist](https://github.com/matguitarist)| A Overseer inspired theme                           | 0.7.14               | [Preview](https://github.com/Kareadita/Themes/blob/main/Native%20Themes/Overseerr/preview.jpg) |
```

**Comment by therobbiedavis** [comment]
> You have conflicts, i believe you need this for the readme:
> 
> ```
> ## Native Themes
> | Theme Name | Author | Description                                         | Kavita Compatibility | Preview | 
> |------------|--------|-----------------------------------------------------|----------------------|---------|
> | Light      | [majora2007](https://github.com/majora2007)    | A light theme for those that don't like dark themes | 0.7.14               | [Preview](https://github.com/Kareadita/Themes/blob/main/Native%20Themes/Light/example.png) |
> | Brilliance | [Elry](https://github.com/ElryWeeb)            | A modern theme for e-ink devices (update for E-Ink) | 0.7.14               | [Preview](https://github.com/Kareadita/Themes/blob/main/Native%20Themes/Brilliance/preview.png) |
> | Nord       | [ice45core0](https://github.com/ice45core0)    | A dark pastel theme using the Nord color palette    | 0.7.14               | [Preview](https://github.com/Kareadita/Themes/blob/main/Native%20Themes/Nord/preview.png) |
> | E-Ink      | [majora2007](https://github.com/majora2007)    | A simplified theme for e-ink devices                | 0.5.2.x              | N/A |
> | Dracula    | @Mat#6627                                      | A Dracula inspired theme                            | ?                    | [Preview](https://github.com/Kareadita/Themes/blob/main/Native%20Themes/Dracula/preview.jpg) |
> | Overseerr  | [Matguitarist](https://github.com/matguitarist)| A Overseer inspired theme                           | 0.7.14               | [Preview](https://github.com/Kareadita/Themes/blob/main/Native%20Themes/Overseerr/preview.jpg) |
> ```

Yeah I recently added the preview column

**Comment by matguitarist** [comment]
add the missing preview column

**Pull request merged**
